server:
  #端口号
  port: 80

spring:
  thymeleaf:
    prefix:
      classpath: /templates/
    mode: LEGACYHTML5
    encoding: UTF-8
  datasource:
    username: root
    password: Wangpd123!
    url: jdbc:mysql://127.0.0.1:3306/mhstudio?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 20GB

mybatis:
  mapper-locations: classpath:/mybatis/mapping/*Mapper.xml
  config-location:  classpath:/mybatis/mybatis-config.xml


upload:
  file:
    path: /opt/fileupload/